language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Lit/ng/cMX0QAPINL6NN0HbAb95kZyL7B1r4Q0TtgIzfaaY4kpA7sjwL5A0Q4E9FCUza63TXFjrv8WtOsjO5/aApDqp7A9FPsIl3xVVFi9F0GC+iRledv13r1kP1uHF2RH/z6d0mo7rTSbPd7tXI1UAORdGo719OiWPdQ9t1sdJrpROQ18JhNGeRT2hRIASqzFwn+adl/gEVr4G53ghiN2m8BpbSnPwLslcH9T1Z2YT1p/BiWpOT6ETCIvxwmqEGBlMtbOel/LSsGp1petFVP//IbixCzhW3eK/KivJXw+UbKT4bx4M5B3Mx104E1IYep+Z4YmtOGhHQE2SPE/zxH/b+FbwgXCa8qviCVbyJlMCwGfmyC4KMheAkBmGvqdzGbFDYRDhrX/BsOmklBSqJt3KQjDrCL6KHFixgdy+Gs44wRdL4oQVGP3pEzncsFIRbb4dW5ewHdVNE1nQ+NkZ8Lfj+A8P7oLJINkssyTX6IstR5KiGwo09POCqD2gZOQBPEjk3RtIYPDLpUXq66+e+u573g3/BkcXrjAnUD5CivxrT1y3d8BH6Q5+ThN3K8O4gEF1IamdKWQirJ3ojqmXtQ6GCn9ZetPBn8fV2ly7sARPOZeYf6aWiCr3zdIionDPa70DuoalWfqTSwOmM2Lm3j+t8pp8tPrGghwF5idxWxRU=
  app: modern-headshots-server
  on:
    repo: anthonyphoto/Modern-Headshots-Server
