language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: BdisR0PR2HjW90zflrXLeGgvnyMT6R0WS1+U8Ck43ULH3xvaJugRfv3/sqxCmuXn5KhU0V9hbJXV0hnP7RdZLgNPt47K4sMMeUJsjbknB6nAvD1KlK+XUI6h9FS2QpFSFwueou+kM5UIQcsaO7f3Sk6BV59x23X09R+/TybxB7cC+B5/jovxdY/pbNQgZM1EpsJz6SiWva1ipBgJhDVtVcioNdNtriYwnbT1PduC+y0IabJZKnsPUKHoz2YYmo3UGxRAVkjKtNr2nRKK5xaNklZxoqZx1/xPk8WIr4hC/yaUocxk1mPIJo2F3rxvOGwo7BMmaso+bWkJpl7gE6uiVQKodUIonwPbX7fxVm1lYNgGD1EDGhy7kJHkUoidPhdKCauLKrRYkfO1ZAgoUS9HL+tvOg7PEJ9tdDMUohCdi225KM0WTxCZmWUGjTROVXCz1pW63Nx8D/r/8aaQU0LrhbqB6NKdomgqYoh1zd1vnQ/ti+e9MVHIHg9KDYnw2x0UmSOLs6CotNmwo74ovVo3ZALdwAn8rSob6J/UqGgrjayUlkE4PFXmT/aZvfmebXCgfe3SS02UDteclAikFKpeX/y2fY01+cltMhQfRuk4mdVfgioN6thCWX0qlm366ZkKQ7mA0ElEtgwmOBPfk57LVwMcsdFKKTOsnzAkBSouUFo=
  app: modern-headshots-server
  on:
    repo: anthonyphoto/Modern-Headshots-Server
